issue_1005
pytorch/serve pull request #1031
Opened 2021-04-10 00:04 UTC by lxning

## Description

Please include a summary of the feature or issue being fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #(issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Feature/Issue validation/testing

Please describe the tests [UT/IT] that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced. 
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- UT/IT execution results

- Logs

## Checklist:

- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] New and existing unit tests pass locally with these changes?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

2021-04-12 17:21 UTC, nskool approved these changes

2021-04-12 17:21 UTC, nskool commented on ts_scripts/install_utils
> +        brew tap AdoptOpenJDK/openjdk
Nit: repetition can be avoided for command `brew tap AdoptOpenJDK/openjdk`

2021-04-15 23:14 UTC, maaquib requested changes

2021-04-15 23:14 UTC, maaquib commented on ts_scripts/install_utils
> +      BREW_VERSION=$(brew --version  2>&1 | head -1 | cut -d' ' -f2)
NIT (Can be done later): We should remove this script completely after removing the 1 [usage](https://github.com/pytorch/serve/blob/master/binaries/pip/build_wheels.sh). No point in having these when we have migrated everything to python

2021-04-15 23:14 UTC, maaquib commented on ts_scripts/install_dependencies.py
> +            return
Shouldn't we `exit(1)` from here instead of continuing onto the next steps?

2021-04-19 18:03 UTC, maaquib approved these changes

2021-04-19 18:35 UTC, merged