FAQ update: international language decode
pytorch/serve pull request #1393
Opened 2022-01-07 18:38 UTC by lxning

## Description

Please include a summary of the feature or issue being fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #(issue)
#1385 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Feature/Issue validation/testing

Please describe the tests [UT/IT] that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced. 
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- UT/IT execution results

- Logs

## Checklist:

- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] New and existing unit tests pass locally with these changes?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

2022-02-07 01:59 UTC, msaroufim requested changes

2022-02-23 05:35 UTC, msaroufim approved these changes

2022-03-09 17:59 UTC, maaquib commented on docs/FAQs.md
> +If a model converts international language string to bytes, client needs to use the codec mechanism specified by the model.
I do see utf-8 decoding in some examples like the [nmt](https://github.com/pytorch/serve/blob/master/examples/nmt_transformer/model_handler_generalized.py#L55) one. We can probably add a reference here

2022-08-16 05:36 UTC, msaroufim commented
@maaquib I Just made your suggestion, can you check this PR again so we can merge?

2022-09-09 18:09 UTC, rohithkrn approved these changes

2022-09-09 19:09 UTC, merged