Use sys.executable instead of hard coding
pytorch/serve pull request #1555
Opened 2022-04-08 05:50 UTC by nijkah

## Description

Predefined 'python' can be different from the command which is really executed.
So replace 'python' with sys.executable

Fixes #(issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

2022-04-08 21:55 UTC, msaroufim approved these changes

2022-04-13 21:59 UTC, maaquib commented
@nijkah Thanks for fixing this. Can you also verify the [sanity suite](https://github.com/pytorch/serve/blob/master/CONTRIBUTING.md) runs fine and then I can merge this

2022-04-14 04:33 UTC, nijkah commented
@maaquib I thought `python torchserve_sanity.py` had been done in `AWS CodeBuild CI Report`s.
Should I run it in my environment? I tested it in the past, but it requires quite a lot of resources compared to my environment.

2022-04-14 18:36 UTC, HamidShojanazeri approved these changes

2022-04-14 18:42 UTC, mreso approved these changes

2022-04-14 18:42 UTC, mreso commented on ts_scripts/install_dependencies.py
> +from shutil import which
This seems to be an unused import

2022-04-14 23:09 UTC, msaroufim requested changes
let
s address mathias feedback

2022-04-18 17:39 UTC, merged