Clarify Kserve api in Readme
pytorch/serve pull request #1723
Opened 2022-07-05 01:56 UTC by SangamSwadiK

Clarify Kserve protocol versions supported in Readme.

## Description

Clarify Kserve protocol versions supported by torchserve, in Readme
Fixes #1721

## Type of change
- [x] This change requires a documentation update ( Readme)

## Feature/Issue validation/testing
Not applicable.

## Checklist:

- [x] Did you have fun?
- [x] Have you made corresponding changes to the documentation?

Please let me know if it needs to be rephrased or documented differently,
Thanks.

2022-07-05 02:18 UTC, msaroufim requested changes
Thanks for this change - I'd suggest we mention our support for the v2 API in 2 more places

`README.md`
`docs/management_api.md`

2022-07-05 02:18 UTC, msaroufim commented on README.md
> +  * [Kserve](https://kserve.github.io/website/modelserving/v1beta1/torchserve/) (Supports both v1 and v2 api)
How about this instead

```suggestion
  * [Kserve](https://kserve.github.io/website/modelserving/v1beta1/torchserve/) : Supports both v1 and v2 API
```

2022-07-05 15:23 UTC, msaroufim approved these changes

2022-07-05 15:23 UTC, msaroufim commented on README.md
> +  * [Kserve](https://kserve.github.io/website/modelserving/v1beta1/torchserve/) (Supports both v1 and v2 api)
Ok one last thing here seeing as how we're only linking to v1beta1 we should also link to v2 here 

`Kserve: Supports both [v1](v_1_link) and [v2](v_2_link) API

2022-07-05 17:16 UTC, maaquib commented on docs/management_api.md
> +Alternatively, if you want to use KServe, TorchServe supports both v1 and v2 API. For more details please look into this [kserve/README.md](https://github.com/pytorch/serve/tree/master/kubernetes/kse
`kserve/README.md` as the hyperlink text can be confusing as someone might try to look up a kserve directory which don't have.

```suggestion
Alternatively, if you want to use KServe, TorchServe supports both v1 and v2 API. For more details please look into this [kserve documentation](https://github.com/pytorch/serve/tree/master/kubernetes/kserve)
```

2022-07-06 05:07 UTC, msaroufim approved these changes

2022-07-07 01:21 UTC, agunapal approved these changes
Looks good

2022-07-07 01:26 UTC, merged