[WIP] fix: volume permission in torchserve kubernetes
pytorch/serve pull request #1747
Opened 2022-07-20 09:55 UTC by jagadeeshi2i

Signed-off-by: jagadeesh <jagadeeshj@ideas2it.com>

## Description

Fixes #1337 
[test.log](https://github.com/pytorch/serve/files/9148626/test.log)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [] This change requires a documentation update

## Checklist:

- [x] Did you have fun?
- [x] Have you added tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

2022-07-20 16:30 UTC, msaroufim approved these changes

2022-07-25 22:02 UTC, agunapal requested changes
@jagadeeshi2i Could you please clarify in the description how this is fixing [1337](https://github.com/pytorch/serve/issues/1337) Also could you please clarify what I am supposed to look at in the test.log. Could you please share the  before/after log?

2022-07-26 08:22 UTC, jagadeeshi2i commented
Hi @agunapal the securityContext fix is not required for native torchserve. As TS mount the PV in `/home/model-server` path which is owned by model-server. The fix was earlier added for other integration like kserve.

2022-07-28 04:44 UTC, chauhang approved these changes

2022-08-15 16:03 UTC, maaquib approved these changes

2022-10-03 16:14 UTC, merged