[WIP] fix: model status API for kserve
pytorch/serve pull request #1773
Opened 2022-07-28 04:02 UTC by jagadeeshi2i

Signed-off-by: jagadeesh <jagadeeshj@ideas2it.com>

## Description
fixes: [kserve/kserve-1915](https://github.com/kserve/kserve/issues/1915)

Please read our [CONTRIBUTING.md](https://github.com/pytorch/serve/blob/master/CONTRIBUTING.md) prior to creating your first pull request.

Please include a summary of the feature or issue being fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #(issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Feature/Issue validation/testing

Please describe the Unit or Integration tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
Logs for Test A

- [ ] Test B
Logs for Test B

## Checklist:

- [ ] Did you have fun?
- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

2022-07-28 04:48 UTC, chauhang commented on kubernetes/kserve/kserve_wrapper/TorchserveModel.py
> +        model_path = '/home/ubuntu/models/model-store'
What is the reason for changing this?

2022-08-08 16:29 UTC, msaroufim commented
@jagadeeshi2i Windows CI is known to flake so CI is all green
![Screen Shot 2022-08-08 at 9 29 24 AM](https://user-images.githubusercontent.com/3282513/183467039-705aefac-027e-4886-8126-648980ad3493.png)

2022-08-29 03:46 UTC, chauhang approved these changes

2022-09-19 22:13 UTC, agunapal requested changes

2022-09-19 22:13 UTC, agunapal commented on kubernetes/kserve/kserve_wrapper/TorchserveModel.py
> +    def load(self) -> bool:
@jagadeeshi2i  Can you please add a docstring for this function

2022-09-19 22:13 UTC, agunapal commented on kubernetes/kserve/kserve_wrapper/__main__.py
> +        model.load()
@jagadeeshi2i  Please add a comment here mentioning why we are loading the model here

2022-09-21 21:09 UTC, agunapal approved these changes
Looks good to me

2022-09-21 21:11 UTC, merged