Use and link to correct paths
pytorch/serve pull request #1805
Opened 2022-08-19 11:00 UTC by jangop

Although, according to a statement towards the beginning of the tutorial, paths were supposed to relative to the repository's root's parent, most were actually relative to the repository's root. The path to the configuration file only contained the filename.

Please note that this commit and pull request only pertain to a single text file. No code changes, no tests, no nothin'.

2022-08-25 01:32 UTC, agunapal commented on examples/image_classifier/mnist/README.md
> +In this example, we show how to use a pre-trained custom MNIST model to perfor real-time digit recognition with TorchServe.
typo .. (perform)

2022-08-26 20:07 UTC, agunapal commented
@jangop  Thanks for submitting this. I appreciate the intent. Please restrict the changes in the PR to the original intent (which is correcting the relative paths) . Please revert all other rewording , unless there is a grammatical error.

2022-10-20 16:21 UTC, maaquib requested changes

2022-10-20 16:21 UTC, maaquib commented on examples/image_classifier/mnist/README.md
> +In this example, we show how to use a pre-trained custom MNIST model to perfor real-time digit recognition with TorchServe.
```suggestion
In this example, we show how to use a pre-trained custom MNIST model to perform real-time digit recognition with TorchServe.
```

2023-01-18 01:38 UTC, msaroufim commented
Closing for now, please reopen if any other issues exist

2023-01-18 01:38 UTC, closed without merging