[WIP] Feat: stable-diffusion-v2
pytorch/serve pull request #2009
Opened 2022-11-28 19:50 UTC by jagadeeshi2i

Signed-off-by: jagadeesh <jagadeeshj@ideas2it.com>

## Description

Please read our [CONTRIBUTING.md](https://github.com/pytorch/serve/blob/master/CONTRIBUTING.md) prior to creating your first pull request.

Please include a summary of the feature or issue being fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #(issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Feature/Issue validation/testing

Please describe the Unit or Integration tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
Logs for Test A

- [ ] Test B
Logs for Test B

## Checklist:

- [ ] Did you have fun?
- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

2022-12-14 01:29 UTC, msaroufim approved these changes

2022-12-14 01:29 UTC, msaroufim commented on examples/diffusers/config.properties
> +model_snapshot={"name":"startup.cfg","modelCount":1,"models":{"stable-diffusion":{"1.0":{"defaultVersion":true,"marName":"stable-diffusion.mar","minWorkers":1,"maxWorkers":1,"batchSize":1,"maxBatchDe
```suggestion
```

2022-12-14 23:18 UTC, maaquib requested changes
```
$ python Download_model.py
Fetching 12 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 28055.55it/s]
The config attributes {'requires_safety_checker': False} were passed to StableDiffusionPipeline, but are not expected and will be ignored. Please verify your model_index.json configuration file.
The config attributes {'prediction_type': 'v_prediction', 'skip_prk_steps': True} were passed to DDIMScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.
Traceback (most recent call last):
  File "Download_model.py", line 6, in <module>
    pipeline = DiffusionPipeline.from_pretrained(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/diffusers/pipeline_utils.py", line 452, in from_pretrained
    if class_name.startswith("Flax"):
AttributeError: 'NoneType' object has no attribute 'startswith'

$ pip freeze | grep diffusers
diffusers==0.6.0
```

@jagadeeshi2i Can you also add `pip install -r requirements.txt` to the readme as a step

2023-01-18 00:39 UTC, agunapal approved these changes

2023-01-18 00:42 UTC, agunapal approved these changes

2023-01-18 02:19 UTC, merged