README for serving models using TorchServe Docker Container
pytorch/serve pull request #2118
Opened 2023-02-09 23:26 UTC by agunapal

## Description

This is a README showing an example for serving models using Docker container

Fixes #(2113)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Feature/Issue validation/testing

The outputs posted in the README are from executing the steps mentioned

## Checklist:

- [ ] Did you have fun?
- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

2023-02-10 16:30 UTC, lxning approved these changes

2023-02-10 18:11 UTC, msaroufim requested changes
I'd prefer if we also delete code from https://github.com/pytorch/serve/blob/master/docker/README.md#create-torch-model-archiver-from-container and just have a single point of truth that's linked from the main README and not just the examples page

2023-02-10 19:14 UTC, agunapal commented
> I'd prefer if we also delete code from https://github.com/pytorch/serve/blob/master/docker/README.md#create-torch-model-archiver-from-container and just have a single point of truth that's linked from the main README and not just the examples page

@msaroufim I'll add a link to the example there. There is probably more than one way to serve the model using docker?

2023-02-16 03:55 UTC, msaroufim approved these changes

2023-02-16 18:59 UTC, merged