[WIP] Add zip-store option to model-archiver tool
pytorch/serve pull request #2196
Opened 2023-03-23 17:53 UTC by mreso

## Description

This PR adds an option to our model-archiver tool to create a mar file without compression. This greatly speeds up the creation of the files which will enable us to reduce unit test time.

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## Feature/Issue validation/testing

Please describe the Unit or Integration tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [X] pytest model-archiver/model_archiver/tests/
```
====================================================================== test session starts =======================================================================
platform linux -- Python 3.9.16, pytest-7.2.2, pluggy-1.0.0
rootdir: /home/ubuntu/serve/model-archiver
plugins: mock-3.10.0, cov-4.0.0
collected 29 items

model-archiver/model_archiver/tests/integ_tests/test_integration_model_archiver.py ...                                                                     [ 10%]
model-archiver/model_archiver/tests/unit_tests/test_model_packaging.py ....                                                                                [ 24%]
model-archiver/model_archiver/tests/unit_tests/test_model_packaging_utils.py .....................                                                         [ 96%]
model-archiver/model_archiver/tests/unit_tests/test_version.py .                                                                                           [100%]

======================================================================= 29 passed in 0.79s =======================================================================
```

## Checklist:

- [X] Did you have fun?
- [X] Have you added tests that prove your fix is effective or that this feature works?
- [X] Has code been commented, particularly in hard-to-understand areas?
- [X] Have you made corresponding changes to the documentation?

2023-03-24 00:54 UTC, msaroufim approved these changes

2023-03-28 21:36 UTC, agunapal requested changes
@mreso Looks good overall Can you please update this README with the new option and may be showing an example in the Readme? https://github.com/pytorch/serve/blob/master/model-archiver/README.md

2023-03-28 23:26 UTC, mreso commented
> @mreso Looks good overall Can you please update this README with the new option and may be showing an example in the Readme? https://github.com/pytorch/serve/blob/master/model-archiver/README.md

Thanks @agunapal I have added the help text but stopped short of an example as use case is primarily testing

2023-03-28 23:28 UTC, agunapal approved these changes

2023-03-28 23:59 UTC, merged