Adding Performance Checklist to site
pytorch/serve pull request #2526
Opened 2023-08-15 19:17 UTC by sekyondaMeta

Adding performance checklist to site. Quick first run at the checklist.
Plan to add this checklist to FAQs page in the future as well. For now, it can be accessed through the performance page.

Fixes #(issue)
Adds to performance information

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Feature/Issue validation/testing

Built pages locally to ensure they work.

## Checklist:

- [ ] Did you have fun?
- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

2023-08-16 01:34 UTC, msaroufim approved these changes

2023-08-16 01:34 UTC, msaroufim commented on docs/performance_checklist.md
> +- Try [torchscript](https://pytorch.org/docs/stable/jit.html), [inference_mode](https://pytorch.org/docs/stable/generated/torch.inference_mode.html), and [optimize_for_inference](https://pytorch.org/
this is quite outdated best to remove this line

2023-08-16 01:35 UTC, msaroufim commented on docs/performance_checklist.md
> +- Use model quantization (i.e., int8) for CPU inference.  Explore different quantization options: dynamic quantization, static quantization, and quantization aware training, as well as tools such as
add note to ensure you check this is actually fast on your hardware

2023-08-16 01:35 UTC, msaroufim commented on docs/performance_checklist.md
> +- Try task parallelism.  Python’s GIL could affect effective multithreading, even for external native code.  For a system with 32 vCPUs, two inference sessions each with 16 threads often have higher
hmm this is no longer relevant now that we have core pinning

2023-08-16 01:36 UTC, msaroufim requested changes
see comments inline

2023-08-16 17:41 UTC, sekyondaMeta commented
> 

Made the updates

2023-08-24 19:15 UTC, chauhang approved these changes

2023-08-24 23:08 UTC, merged