[WIP] LLM with cpp backend
pytorch/serve pull request #2527
Opened 2023-08-16 18:43 UTC by shrinath-suresh

## Description

Adding example for LLM with torchserve cpp backend

Please read our [CONTRIBUTING.md](https://github.com/pytorch/serve/blob/master/CONTRIBUTING.md) prior to creating your first pull request.

Please include a summary of the feature or issue being fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #(issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Feature/Issue validation/testing

Please describe the Unit or Integration tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
Logs for Test A

- [ ] Test B
Logs for Test B

## Checklist:

- [ ] Did you have fun?
- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

2023-09-14 10:45 UTC, mreso requested changes
Thanks for your contribution! Left a couple of comments.

2023-09-14 10:45 UTC, mreso commented on cpp/src/examples/CMakeLists.txt
Would be good to create a CMakeLists.txt in the llamacpp directory and use add_subdirectory() in the main file to avoid the main one to getting too crowded.

2023-09-14 10:45 UTC, mreso commented on cpp/src/examples/CMakeLists.txt
> +set(MY_OBJECT_FILES
Where are the src files to these obj files?

2023-09-14 10:45 UTC, mreso commented on cpp/src/examples/llamacpp/config.json
> +"checkpoint_path" : "/home/ubuntu/llama-2-7b-chat.Q4_0.gguf"
ditto also: How big is this file?

2023-09-14 10:45 UTC, mreso commented on cpp/src/examples/llamacpp/llamacpp_handler.cc
> +      const int max_tokens_list_size = max_context_size - 4;
Always good to give the magic numbers a name to clarify the purpose?

2023-09-14 10:45 UTC, mreso commented on cpp/src/examples/llamacpp/llamacpp_handler.cc
> +  for (auto id : long_vector) {
Why do we jump through so many loop here? Cant we directly write the tokens_list from the tensor? Or can you create an array using the data_ptr as underlying storage without making a copy?

2023-09-14 10:45 UTC, mreso commented on cpp/src/examples/llamacpp/llamacpp_handler.cc
> +    auto n_vocab = llama_n_vocab(llama_ctx);
Good to avoid auto for primitive datatypes when readability is not suffering.

2023-09-14 10:45 UTC, mreso commented on cpp/src/examples/llamacpp/llamacpp_handler.cc
> +  llama_free(llama_ctx);
Can the model be reused? Then this should be  moved into the destructor.

2023-09-15 09:31 UTC, shrinath-suresh commented
@mreso Thanks for your review comments. I have already addressed few of your comments - implementing destructor, batch processing, remove `auto` based on your previous comments in babyllama PR. Will address the remaining ones and let you know.

2024-03-11 22:16 UTC, lxning commented
This feature was picked up in v0.10.0 task.

2024-03-11 22:16 UTC, closed without merging