(WIP)A guide for loading models in TorchServe
pytorch/serve pull request #2592
Opened 2023-09-13 22:34 UTC by agunapal

## Description

Please read our [CONTRIBUTING.md](https://github.com/pytorch/serve/blob/master/CONTRIBUTING.md) prior to creating your first pull request.

Please include a summary of the feature or issue being fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #(issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Feature/Issue validation/testing

Please describe the Unit or Integration tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
Logs for Test A

- [ ] Test B
Logs for Test B

## Checklist:

- [ ] Did you have fun?
- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

2023-09-13 22:45 UTC, msaroufim requested changes
On whether handler has an initialize method i think it's more nuanced, someone could also be calling `super()`
The model type node makes a lot of sense
in the self contained package node i didn't really understand what you were trying to say because serialized file node intersects with torchscript and onnx. The righthand bottom node should be is your model large and do you care about model initialization time

2023-09-13 23:03 UTC, agunapal commented
@msaroufim Thanks. Agree with both. Changed both

2023-09-13 23:19 UTC, msaroufim commented
top part looks much clearer

bottom still unclear you ask two questions in the node so if i say yes its unclear which part i should go to


<img width="917" alt="Screenshot 2023-09-13 at 4 18 32 PM" src="https://github.com/pytorch/serve/assets/3282513/cf4c87a2-22d4-402e-95fc-02657b3b8f62">

Also in the bottom row theres rows going both ways with no labels

also there's too much text in the large model thing

2023-09-13 23:29 UTC, agunapal commented
> top part looks much clearer
> 
> The first node in the photo i think deciision should be do you want a self contained artifact or do you want fast model loads
> 
> <img alt="Screenshot 2023-09-13 at 4 18 32 PM" width="917" src="https://user-images.githubusercontent.com/3282513/267810635-cf4c87a2-22d4-402e-95fc-02657b3b8f62.png">
> Also in the bottom row theres arrows going both ways with no labels
> 
> also there's too much text in the large model thing

Got it. Let me think about how to address it

2023-09-14 21:41 UTC, agunapal commented
@msaroufim Changed the bottom part a bit. If the model is large, we want users to not package the model at all. So, I think that should be the starting point

2023-09-15 00:47 UTC, msaroufim approved these changes

2023-09-15 01:06 UTC, merged