(WIP)Add support for torch exported model
pytorch/serve pull request #2812
Opened 2023-11-28 20:07 UTC by agunapal

## Description

This PR adds support for 
- Loading torch.export model
- Includes an example of ResNet 18
- Adds a pytest for torch.export

Fixes #(issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Feature/Issue validation/testing

Please describe the Unit or Integration tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

```
================================================================================== test session starts ===================================================================================
platform linux -- Python 3.8.18, pytest-7.3.1, pluggy-1.0.0 -- /home/ubuntu/anaconda3/envs/torchserve/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/ubuntu/serve/test/pytest/.hypothesis/examples')
rootdir: /home/ubuntu/serve
plugins: mock-3.10.0, anyio-3.6.1, cov-4.1.0, hypothesis-6.54.3
collected 1 item                                                                                                                                                                         

test_torch_export.py::test_execute_script_in_custom_directory PASSED                                                                                                               [100%]

==================================================================================== warnings summary ====================================================================================
test_torch_export.py:3
  /home/ubuntu/serve/test/pytest/test_torch_export.py:3: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    from pkg_resources import packaging

../../../anaconda3/envs/torchserve/lib/python3.8/site-packages/pkg_resources/__init__.py:2871
  /home/ubuntu/anaconda3/envs/torchserve/lib/python3.8/site-packages/pkg_resources/__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

../../../anaconda3/envs/torchserve/lib/python3.8/site-packages/pkg_resources/__init__.py:2871
../../../anaconda3/envs/torchserve/lib/python3.8/site-packages/pkg_resources/__init__.py:2871
  /home/ubuntu/anaconda3/envs/torchserve/lib/python3.8/site-packages/pkg_resources/__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

../../../anaconda3/envs/torchserve/lib/python3.8/site-packages/torchvision/transforms/_functional_pil.py:242
  /home/ubuntu/anaconda3/envs/torchserve/lib/python3.8/site-packages/torchvision/transforms/_functional_pil.py:242: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
    interpolation: int = Image.BILINEAR,

../../../anaconda3/envs/torchserve/lib/python3.8/site-packages/torchvision/transforms/_functional_pil.py:288
  /home/ubuntu/anaconda3/envs/torchserve/lib/python3.8/site-packages/torchvision/transforms/_functional_pil.py:288: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
    interpolation: int = Image.NEAREST,

../../../anaconda3/envs/torchserve/lib/python3.8/site-packages/torchvision/transforms/_functional_pil.py:304
  /home/ubuntu/anaconda3/envs/torchserve/lib/python3.8/site-packages/torchvision/transforms/_functional_pil.py:304: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
    interpolation: int = Image.NEAREST,

../../../anaconda3/envs/torchserve/lib/python3.8/site-packages/torchvision/transforms/_functional_pil.py:321
  /home/ubuntu/anaconda3/envs/torchserve/lib/python3.8/site-packages/torchvision/transforms/_functional_pil.py:321: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
    interpolation: int = Image.BICUBIC,

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================================= 1 passed, 8 warnings in 8.73s ============================================================================
```

## Checklist:

- [ ] Did you have fun?
- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

2023-11-28 20:51 UTC, msaroufim requested changes
Right now there is no reason to just export a model, you want to combine this with an aot inductor tutorial so people can get ahead of time compilation and avoid cold starts

2023-11-28 20:51 UTC, msaroufim commented on examples/pt2/torch_export/README.md
> +# TorchServe inference with torch export model
there were some export related details on the main README as well could you consolidate?

2023-11-28 20:51 UTC, msaroufim commented on examples/pt2/torch_export/README.md
> +Change directory to the root of `serve`
cd serve is simpler

2023-11-28 20:51 UTC, msaroufim commented on examples/pt2/torch_export/README.md
> +- JIT vs AOT
this needs a longer elaboration

2023-11-28 20:51 UTC, msaroufim commented on examples/pt2/torch_export/README.md
> +torch-model-archiver --model-name res18-pt2 --handler image_classifier --version 1.0 --serialized-file resnet18.pt2 --extra-files ./examples/image_classifier/index_to_name.json
you need to update the archiver code docstrings as well

2023-11-28 20:52 UTC, msaroufim requested changes

2023-11-28 20:52 UTC, msaroufim commented on examples/pt2/torch_export/README.md
> +`torch.export` differs from `torch.compile` is a few ways
you need to combo aot inductor with this story

2023-11-29 23:00 UTC, agunapal commented
torch.export.export by itself only creates an FX Graph representation of the model and serializes it. So, at inference, the model is executed in eager. Hence, even though this works, closing this PR as it doesn't make use of torch.compile

2023-11-29 23:00 UTC, closed without merging