[WIP] Draft use cases for torchserve
pytorch/serve pull request #629
Opened 2020-08-19 15:03 UTC by dhaniram-kshirsagar

## Description

Please include a summary of the feature or issue being fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #(issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Feature/Issue validation/testing

Please describe the tests [UT/IT] that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced. 
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- UT/IT execution results

- Logs

## Checklist:

- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] New and existing unit tests pass locally with these changes?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

2020-09-02 19:54 UTC, dhanainme requested changes
Please share some context on the specific ask for which this doc was created.

2020-09-23 11:48 UTC, dhaniram-kshirsagar commented
> Please share some context on the specific ask for which this doc was created.

As discussed offline, this is mainly targeted towards users who don't have proper development background and are here for addressing a particular DL use case. Accordingly, we have listed a few of the use cases and many more can be added in the future.

2020-10-26 16:05 UTC, HamidShojanazeri approved these changes

2020-10-30 19:07 UTC, lxning approved these changes

2020-11-26 00:02 UTC, merged