Issue 648
pytorch/serve pull request #686
Opened 2020-09-17 12:32 UTC by maheshambule

## Description

- This PR adds support in base handler to invoke the Torch C++ API to load TorchScript model and to do inference on it.
- The model_archiver script is modified to accept torch-api-type (either python or cpp) value. Based on the value of Python or CPP API will be invoked by the handler.
- The registration API is modified to accept 'torch_api_type' parameter. The value provided to the registration API will override the Manifest value. If torch_api_type parameter is not provided Manifest.json value will be used. If Manifest.json does not have 'torchAPIType', by default 'python' will be used.
- The torch_api_type value will be passed to the handler context. It is up to the handler, to use this property.
- The user can extend and write their own custom binding based on the binding code provided in this PR

Fixes #(issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Feature/Issue validation/testing

Test case is added in sanity suite.

- UT/IT execution results

- Logs

## Checklist:

- [ X] Have you added tests that prove your fix is effective or that this feature works?
- [ X] New and existing unit tests pass locally with these changes?
- [ X] Has code been commented, particularly in hard-to-understand areas?
- [ X] Have you made corresponding changes to the documentation?

2020-09-17 12:42 UTC, maheshambule commented
@maaquib, @dhanainme Could you please help in reviewing this PR?

2020-09-18 10:09 UTC, maheshambule commented on docs/management_api.md
> +* `torch_api_type` - the Torch API type to be used by the handler. This value will override `torchAPIType` in MANIFEST.json. If not provided, `torchAPIType` from MANIFEST.json will be used.
We can have a different property name instead of 'torchAPIType'.  Suggestions are welcome.

2020-09-22 06:17 UTC, dhanainme commented
Please add 
*  Example in the example folder / Model Zoo
* Regression test suite using the model Zoo

2020-10-03 17:22 UTC, chauhang requested changes
@maheshambule Thanks for getting this work started. In future it will be better to have a design discussion before submitting PRs for a major feature like this. 

Changes are needed to add direct support for invoking C++ backend instead of going through python via pybind. Please run performance comparison benchmark between python and C++ backend for the same models for performance benefits observed with the new solution. Other comments are inline

2020-10-03 17:22 UTC, chauhang commented on .circleci/scripts/linux_test_sanity.sh
> +torch_api_support=("python" "python" "python" "python" "python" "both" "python" "python" "python" "python")
@maheshambule Why is "python" being repeated here so many times?

2020-10-03 17:22 UTC, chauhang commented on examples/cpp_handler/README.md
> +Since handler runs in Python worker process, in order to invoke C++ API, you need to provide the Python torch_cpp_python_bindings
@maheshambule Can you please explain why we need the Python worker to invoke the C++ API? The whole purpose of introducing support for C++ backend is for performance for fast inference. Why is it not possible to call C++ api directly from the Java FE Rest APIs?

2020-10-03 17:22 UTC, chauhang commented on frontend/server/src/main/java/org/pytorch/serve/wlm/Model.java
> +                this.torchAPIType = ConfigManager.getInstance().getTsDefaultTorchAPIType();
For customer upgrading existing deployments to new release, the default should be set to Python even when there is no value specified in the config file. Will this handle for upgrade scenarios?

2020-10-03 17:22 UTC, chauhang commented on model-archiver/README.md
> +                        This is an optional parameter.
Clarify details for the default when no value is specified

2020-10-03 17:22 UTC, chauhang commented on ts/torch_handler/base_handler.py
> +                    raise Exception("Keyword arguments are not supported by CPP API. Use Python API instead.")
What are the kwargs used for at present for python side? Can you please clarify, what aspects will not work with C++ due to this with an example?

2020-10-05 15:14 UTC, maheshambule commented
@chauhang, Thanks for the review and comments.
We have a design document for the feature here:
https://docs.google.com/document/d/1ojYTtK3XfOWj_fQ3PhgGCcvi7a7ojjzcJTcEmJk4-Hs/edit?usp=sharing

Before working on the feature, we did some experiments and we found that C++ with Python bindings (as implemented by this PR) will not and is not supposed to give any performance boost. We also found that the current Python worker overhead is very minimal and in order to utilize C++ backend to gain a performance boost, we need to consider major changes in frontend as well. All the experiments results are present in the document above.

2021-03-15 22:11 UTC, lxning commented
@maheshambule we found load model is expensive in Python. vs in C++ lib. Frontend should directly start C++ based backend as @chauhang comments if the model is C++ based.

2021-05-12 01:17 UTC, msaroufim commented
@AshkanAliabadi can I close this PR?

2021-05-13 20:59 UTC, closed without merging