Migrate model urls
pytorch/serve pull request #697
Opened 2020-09-23 22:41 UTC by jeremiahschung

## Description

Applying broader changes over the codebase to use the pytorch.org based URL for model assets. See related [PR 696](https://github.com/pytorch/serve/pull/696) 

Fixes #(issue) - no existing issue 

## Type of change

Please delete options that are not relevant.
- [x] This change requires a documentation update

## Feature/Issue validation/testing

Please describe the tests [UT/IT] that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced. 
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- UT/IT execution results

- Logs

## Checklist:

- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] New and existing unit tests pass locally with these changes?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

2020-09-24 18:01 UTC, chauhang requested changes
@jeremiahschung Thanks for submitting this PR. Please ensure all the items that involve code changes have been verified and attach the test outputs as part of the PR.

2020-10-01 02:35 UTC, jeremiahschung commented on docs/configuration.md
> +allowed_urls=https://s3.amazonaws.com/.*,https://torchserve.pytorch.org/.*
Tested the allowed_urls option and attached log in the PR description. Also updated with regression test log results which call into the management API utilizing the new URLs. Also added EKS standup test results.

2020-10-05 16:51 UTC, chauhang approved these changes

2020-10-05 17:24 UTC, maaquib approved these changes

2020-10-05 17:25 UTC, merged