Fixed bug in create_mar.sh script of Text_to_Speech_Synthesizer
pytorch/serve pull request #704
Opened 2020-09-28 14:38 UTC by AshwinChafale

## Description

Fixed a bug in create_mar.sh script of "text_to_speech_synthesizer" model.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2020-09-29 18:32 UTC, maaquib commented on examples/text_to_speech_synthesizer/create_mar.sh
>  wget https://github.com/nvidia/DeepLearningExamples/archive/torchhub.zip
Why not just use `-O` to overwrite the file?
```suggestion
wget -O https://github.com/nvidia/DeepLearningExamples/archive/torchhub.zip torchhub.zip
```

2020-09-29 18:34 UTC, maaquib requested changes
Inline comment

2020-09-30 16:40 UTC, maaquib requested changes

2020-09-30 16:40 UTC, maaquib commented on examples/text_to_speech_synthesizer/create_mar.sh
> +if [ -d "DeepLearningExamples-torchhub" ]
Use wget with -O instead of all the if-else statements

2020-09-30 18:09 UTC, maaquib requested changes

2020-09-30 18:09 UTC, maaquib commented on examples/text_to_speech_synthesizer/create_mar.sh
> +   rm tacotron.zip
Doesn't `rm -rf tacotron.zip` suffice? What's the reason for using an `if`

2020-10-17 15:45 UTC, chauhang approved these changes

2020-10-19 21:30 UTC, maaquib approved these changes

2020-10-19 21:49 UTC, merged