[WIP] Add EKS troubleshooting steps
pytorch/serve pull request #723
Opened 2020-10-12 23:04 UTC by jeremiahschung

Add troubleshooting scenarios and reorganize the troubleshooting section of the document.

## Description

Documentation change to add troubleshooting cases for the EKS setup.

Fixes #384 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Feature/Issue validation/testing
N/A. Only a doc change.

## Checklist:

- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] New and existing unit tests pass locally with these changes?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [x] Have you made corresponding changes to the documentation?

2020-10-19 22:27 UTC, maaquib requested changes

2020-10-19 22:27 UTC, maaquib commented on kubernetes/README.md
> +  * Inspect your Cloudformation console's events tab to diagonize any possible issues. You should able be able to find the following resources at the end of this step in the respective AWS consoles
```suggestion
  * Inspect your Cloudformation console's events tab to diagonize any possible issues. You should be able to find the following resources at the end of this step in the respective AWS consoles
```

2020-10-20 00:36 UTC, maaquib approved these changes

2020-10-20 18:21 UTC, dhanainme approved these changes

2020-10-20 18:57 UTC, merged