Update README.md
pytorch/serve pull request #731
Opened 2020-10-16 04:50 UTC by jeremiahschung

## Description

The kitten.jpg link previously hosted on S3 no longer works. Changing to pull directly from the torchserve GitHub repo.

Fixes #(issue) - No issue created

## Type of change

Please delete options that are not relevant.
- [x] This change requires a documentation update

## Feature/Issue validation/testing

Fetch the cat image and call the prediction endpoint. Verify it works.

- Logs
```
ubuntu@ip-172-31-22-19:~$ curl -O https://raw.githubusercontent.com/pytorch/serve/master/docs/images/kitten_small.jpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7341  100  7341    0     0   159k      0 --:--:-- --:--:-- --:--:--  159k
ubuntu@ip-172-31-22-19:~$ curl http://127.0.0.1:8080/predictions/densenet161 -T kitten_small.jpg 
{
  "tabby": 0.5078840851783752,
  "lynx": 0.18985284864902496,
  "tiger_cat": 0.16152925789356232,
  "tiger": 0.05462226644158363,
  "Egyptian_cat": 0.04894305393099785
```

## Checklist:

- [x] Have you made corresponding changes to the documentation?

2020-10-16 05:05 UTC, harshbafna requested changes
The same URL is used at multiple places

 - benchmark/benchmark.py
 - cloudformation/README.md
 - docs/inference_api.md
 
Please update them as well.

2020-10-16 05:17 UTC, jeremiahschung commented
Missed a no brainer. Thank you for pointing out. Made fixes to the other locations!

2020-10-17 00:34 UTC, chauhang approved these changes

2020-10-19 21:21 UTC, maaquib approved these changes

2020-10-19 21:21 UTC, merged