Add request envelope to support Multiserving frameworks
pytorch/serve pull request #749
Opened 2020-10-23 14:25 UTC by abishekchiff

## Description

Adds the wrapper feature to help Multiserving frameworks
Resolved the conflicts in the PR https://github.com/pytorch/serve/pull/521 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Feature/Issue validation/testing

Additional units added to ts/torch_handler/unit_tests. Build completes successfully.

## Checklist:

- [x] Have you added tests that prove your fix is effective or that this feature works?
- [x] New and existing unit tests pass locally with these changes?
- [x] Has code been commented, particularly in hard-to-understand areas?
- [x] Have you made corresponding changes to the documentation?

2020-11-02 01:41 UTC, chauhang commented
@abishekchiffon Thanks for getting this PR ready. Can you please attach the detailed testing logs as well?

2020-11-20 00:52 UTC, maaquib commented
@abishekchiffon Seeing failures when running the unit test `python -m pytest test_envelopes.py`

```
========================================================================= short test summary info ==========================================================================
ERROR test_envelopes.py::test_json - RuntimeError: Missing the model.pt file
ERROR test_envelopes.py::test_json_batch - RuntimeError: Missing the model.pt file
ERROR test_envelopes.py::test_json_double_batch - RuntimeError: Missing the model.pt file
ERROR test_envelopes.py::test_body - RuntimeError: Missing the model.pt file
======================================================================= 1 passed, 4 errors in 0.55s ========================================================================
```

2020-11-20 01:44 UTC, maaquib requested changes
@abishekchiffon Seeing failures when running the unit test `python -m pytest test_envelopes.py`

```
========================================================================= short test summary info ==========================================================================
ERROR test_envelopes.py::test_json - RuntimeError: Missing the model.pt file
ERROR test_envelopes.py::test_json_batch - RuntimeError: Missing the model.pt file
ERROR test_envelopes.py::test_json_double_batch - RuntimeError: Missing the model.pt file
ERROR test_envelopes.py::test_body - RuntimeError: Missing the model.pt file
======================================================================= 1 passed, 4 errors in 0.55s ========================================================================
```

2020-11-20 15:58 UTC, abishekchiffon commented on frontend/server/src/main/java/org/pytorch/serve/util/codec/ModelRequestEncoder.java
> +            // TODO: this might be a bug. If handler isn't specified, this
I will create an issue for the bug.

2020-11-20 16:15 UTC, abishekchiffon commented on docs/default_handlers.md
> +1. Run and update the unit tests in [unit_tests](https://github.com/pytorch/serve/tree/master/ts/torch_handler/unit_tests). As always, make sure to run [torchserve_sanity.sh](https://github.com/pytor
**The test suite can be either ran by the   `./ts/torch_handler/unit_tests/run_unit_tests.sh`** command or by running
`python -m pytest test_envelopes.py` after the model artifacts are moved to the _ts/torch_handler/unit_tests/models/tmp_ folder.
As all the unit test files requires the model artifacts to be present inside _'tmp'_ folder. These model artifacts are downloaded or moved to the _'tmp'_ in '[ts/torch_handler/unit_tests/run_unit_tests.sh](https://github.com/abishekchiffon/serve/blob/issue_411_envelope/ts/torch_handler/unit_tests/run_unit_tests.sh)' and deleted on completion.

2020-11-20 16:19 UTC, abishekchiffon commented on docs/default_handlers.md
> +1. Run and update the unit tests in [unit_tests](https://github.com/pytorch/serve/tree/master/ts/torch_handler/unit_tests). As always, make sure to run [torchserve_sanity.sh](https://github.com/pytor
> Made the suggested change in the default_handlers.

2020-11-20 16:21 UTC, abishekchiffon commented on docs/default_handlers.md
> +1. Run and update the unit tests in [unit_tests](https://github.com/pytorch/serve/tree/master/ts/torch_handler/unit_tests). As always, make sure to run [torchserve_sanity.sh](https://github.com/pytor
Made the suggested change in the default_handlers.

2020-11-23 07:13 UTC, chauhang approved these changes

2020-11-23 22:15 UTC, dhanainme approved these changes

2020-11-23 22:16 UTC, merged