[WIP - Do not review] - Workflow support
pytorch/serve pull request #785
Opened 2020-11-17 12:18 UTC by dhaniram-kshirsagar

## Description

Please include a summary of the feature or issue being fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #(issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Feature/Issue validation/testing

Please describe the tests [UT/IT] that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced. 
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- UT/IT execution results

- Logs

## Checklist:

- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] New and existing unit tests pass locally with these changes?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

2021-01-29 23:29 UTC, dhanainme commented
These ~150 files have been split to the following branches for more managable 



- issue_682_workflow_archiver_frontend                     293ec798 Frontend Ensemble Code
- issue_682_workflow_archiver_frontend_test                a35f1699 Frontend Java Workflow Archive Tests
- issue_682_workflow_archiver_py                           ba7a9d12 Workflow Archiver Tool
- issue_682_workflow_backend                               11b62dab Workflow backend changes
- issue_682_workflow_scripts                               8ead3c30 Workflow - Updates to scripts
- issue_682_workflow_server_docs_examples                  675cef1b Workflow updates to Docs & Examples
- issue_682_workflow_server_ensemble                       a6e1362c Gradle changes
- issue_682_workflow_server_http                           1c3b5d78 Frontend Java code changes for HTTP / GRPC
- issue_682_workflow_server_test                           0fdbcf06 Workflow test updates
- issue_682_workflow_server_wlm_utils                      ea214155 Gradle / Server updates
- issue_682_workflow_server_workflowcode                   d5ad80f1 Java Frontend Server Workflow Code



**issue_682_workflow_server_docs_examples**

M       README.md
M       docs/README.md
M       docs/configuration.md
M       docs/rest_api.md
M       docs/server.md
A       docs/workflow_inference_api.md
A       docs/workflow_management_api.md
A       docs/workflows.md
A       examples/Workflows/README.md
A       examples/Workflows/densenet_image_classifier_pipeline/README.md
R100    frontend/modelarchive/src/test/resources/models/noop_no_archive/noop/model.pt   examples/Workflows/densenet_image_classifier_pipeline/densenet_model/README.md
A       examples/Workflows/densenet_image_classifier_pipeline/densenet_model/densenet_handler.py
A       examples/Workflows/densenet_image_classifier_pipeline/densenet_model/model.py
A       examples/Workflows/densenet_image_classifier_pipeline/densenet_workflow.yaml
A       examples/Workflows/densenet_image_classifier_pipeline/densenet_workflow_handler.py
A       examples/Workflows/densenet_image_classifier_pipeline/index_to_name.json
A       examples/Workflows/densenet_image_classifier_pipeline/kitten.jpg



**issue_682_workflow_archiver_frontend**

R100    frontend/modelarchive/build.gradle      frontend/archive/build.gradle
R100    frontend/modelarchive/gradlew   frontend/archive/gradlew
R084    frontend/modelarchive/src/main/java/org/pytorch/serve/archive/DownloadModelException.java       frontend/archive/src/main/java/org/pytorch/serve/archive/DownloadArchiveException.java
R096    frontend/modelarchive/src/main/java/org/pytorch/serve/archive/InvalidModelException.java        frontend/archive/src/main/java/org/pytorch/serve/archive/model/InvalidModelException.java
R098    frontend/modelarchive/src/main/java/org/pytorch/serve/archive/Manifest.java     frontend/archive/src/main/java/org/pytorch/serve/archive/model/Manifest.java
R058    frontend/modelarchive/src/main/java/org/pytorch/serve/archive/ModelArchive.java frontend/archive/src/main/java/org/pytorch/serve/archive/model/ModelArchive.java
R096    frontend/modelarchive/src/main/java/org/pytorch/serve/archive/ModelException.java       frontend/archive/src/main/java/org/pytorch/serve/archive/model/ModelException.java
R096    frontend/modelarchive/src/main/java/org/pytorch/serve/archive/ModelNotFoundException.java       frontend/archive/src/main/java/org/pytorch/serve/archive/model/ModelNotFoundException.java
R096    frontend/modelarchive/src/main/java/org/pytorch/serve/archive/ModelVersionNotFoundException.java        frontend/archive/src/main/java/org/pytorch/serve/archive/model/ModelVersionNotFoundException.java
A       frontend/archive/src/main/java/org/pytorch/serve/archive/utils/ArchiveUtils.java
R095    frontend/modelarchive/src/main/java/org/pytorch/serve/archive/HexUtils.java     frontend/archive/src/main/java/org/pytorch/serve/archive/utils/HexUtils.java
A       frontend/archive/src/main/java/org/pytorch/serve/archive/utils/InvalidArchiveURLException.java
R067    frontend/modelarchive/src/main/java/org/pytorch/serve/archive/ZipUtils.java     frontend/archive/src/main/java/org/pytorch/serve/archive/utils/ZipUtils.java
A       frontend/archive/src/main/java/org/pytorch/serve/archive/workflow/InvalidWorkflowException.java
A       frontend/archive/src/main/java/org/pytorch/serve/archive/workflow/Manifest.java
A       frontend/archive/src/main/java/org/pytorch/serve/archive/workflow/WorkflowArchive.java
A       frontend/archive/src/main/java/org/pytorch/serve/archive/workflow/WorkflowException.java
A       frontend/archive/src/main/java/org/pytorch/serve/archive/workflow/WorkflowNotFoundException.java



**issue_682_workflow_archiver_frontend_test**

A       frontend/archive/src/test/java/org/pytorch/serve/archive/CoverageTest.java
R082    frontend/modelarchive/src/test/java/org/pytorch/serve/archive/ModelArchiveTest.java     frontend/archive/src/test/java/org/pytorch/serve/archive/model/ModelArchiveTest.java
A       frontend/archive/src/test/java/org/pytorch/serve/archive/workflow/WorkFlowArchiveTest.java
R100    frontend/modelarchive/src/test/java/org/pytorch/serve/test/TestHelper.java      frontend/archive/src/test/java/org/pytorch/serve/test/TestHelper.java
R100    frontend/modelarchive/src/test/resources/models/custom_invalid_python_dep.mar   frontend/archive/src/test/resources/models/custom_invalid_python_dep.mar
R100    frontend/modelarchive/src/test/resources/models/custom_python_dep.mar   frontend/archive/src/test/resources/models/custom_python_dep.mar
R100    frontend/modelarchive/src/test/resources/models/echo.mar        frontend/archive/src/test/resources/models/echo.mar
R100    frontend/modelarchive/src/test/resources/models/error_batch.mar frontend/archive/src/test/resources/models/error_batch.mar
R100    frontend/modelarchive/src/test/resources/models/init-error.mar  frontend/archive/src/test/resources/models/init-error.mar
R100    frontend/modelarchive/src/test/resources/models/loading-memory-error.mar        frontend/archive/src/test/resources/models/loading-memory-error.mar
R100    frontend/modelarchive/src/test/resources/models/mnist.mar       frontend/archive/src/test/resources/models/mnist.mar
R100    frontend/modelarchive/src/test/resources/models/mnist_scripted.mar      frontend/archive/src/test/resources/models/mnist_scripted.mar
R100    frontend/modelarchive/src/test/resources/models/mnist_traced.mar        frontend/archive/src/test/resources/models/mnist_traced.mar
R100    frontend/modelarchive/src/test/resources/models/noop-no-manifest.mar    frontend/archive/src/test/resources/models/noop-no-manifest.mar
R100    frontend/modelarchive/src/test/resources/models/noop-v1.0-config-tests.mar      frontend/archive/src/test/resources/models/noop-v1.0-config-tests.mar
R100    frontend/modelarchive/src/test/resources/models/noop.mar        frontend/archive/src/test/resources/models/noop.mar
R100    frontend/modelarchive/src/test/resources/models/noop_entrypntfunc.mar   frontend/archive/src/test/resources/models/noop_entrypntfunc.mar
R100    frontend/modelarchive/src/test/resources/models/noop_handlername.mar    frontend/archive/src/test/resources/models/noop_handlername.mar
R100    frontend/modelarchive/src/test/resources/models/noop_no_archive/noop/MAR-INF/MANIFEST.json      frontend/archive/src/test/resources/models/noop_no_archive/noop/MAR-INF/MANIFEST.json
A       frontend/archive/src/test/resources/models/noop_no_archive/noop/model.pt
R100    frontend/modelarchive/src/test/resources/models/noop_no_archive/noop/service.py frontend/archive/src/test/resources/models/noop_no_archive/noop/service.py
R100    frontend/modelarchive/src/test/resources/models/noop_v2.mar     frontend/archive/src/test/resources/models/noop_v2.mar
R100    frontend/modelarchive/src/test/resources/models/prediction-memory-error.mar     frontend/archive/src/test/resources/models/prediction-memory-error.mar
R100    frontend/modelarchive/src/ [...]

2021-02-05 23:07 UTC, dhanainme commented
## Steps to perform a simple test in a DL AMI


** Clone Repo / Install Torchserve / WF Archiver / Model Archiver**

```
mkdir workflow
cd workflow/
git clone https://github.com/pytorch/serve
cd serve
git checkout issue_682
pip install . 


cd model-archiver/
pip install . 
cd ..

cd workflow-archiver/
pip install 
cd ..

```

** Create WF / Model Archives and move to a Model store - /tmp/workflow_test/**

```
cd examples/Workflows/densenet_image_classifier_pipeline/densenet_model

wget https://download.pytorch.org/models/densenet161-8d451a50.pth

torch-model-archiver --model-name densenet_wf --version 1.0 --model-file model.py --serialized-file densenet161-8d451a50.pth --handler densenet_handler.py

cd .. 

torch-workflow-archiver --workflow-name densenet --spec-file densenet_workflow.yaml --handler densenet_workflow_handler.py --extra-files index_to_name.json

mkdir /tmp/workflow_test/
mv densenet.war /tmp/workflow_test/
mv densenet_model/densenet_wf.mar /tmp/workflow_test/

```


** Start TS; Test WF Register; List; Inference; Model Register **
```
torchserve --start --model-store /tmp/workflow_test/ --workflow-store /tmp/workflow_test/

curl -X POST "http://127.0.0.1:8081/workflows?url=densenet.war"

curl http://localhost:8081/workflows/

curl http://127.0.0.1:8081/models/

curl http://localhost:8081/workflows/densenet

curl -X POST "http://127.0.0.1:8081/workflows?url=densenet.war"

curl http://127.0.0.1:8080/wfpredict/densenet -T kitten.jpg

```

Issue 
https://github.com/pytorch/serve/issues/682

PR 
https://github.com/pytorch/serve/pull/785


Workflow Spec Yaml
* serve/examples/Workflows/densenet_image_classifier_pipeline/densenet_workflow.yaml


Docs : 
* https://github.com/pytorch/serve/blob/issue_682/docs/workflows.md
* https://github.com/pytorch/serve/blob/issue_682/docs/workflow_management_api.md
* https://github.com/pytorch/serve/blob/issue_682/docs/workflow_inference_api.md



Known issues : 
https://github.com/pytorch/serve/blob/issue_682/docs/workflows.md#known-issues


WF Scenarios planned for support : 
https://docs.google.com/spreadsheets/d/1x_Rj5xczANznVRJBaMrU0Wkhy-z-uWasrS4bzkQ7s3c/edit?ts=5f882aa5#gid=0
Only Pipeline scenario supported now.

2021-02-09 22:48 UTC, dhanainme requested changes
Reviewed Ensemble DAG related changes

* Lombok / final (To be fixed)
* Usage of Guava / ListenableFuture / Yaml lib (Create issues)

2021-02-09 22:48 UTC, dhanainme commented on frontend/server/src/main/java/org/pytorch/serve/ensemble/Node.java
> +    private WorkflowModel workflowModel;
final / Lombok

2021-02-09 22:48 UTC, dhanainme commented on frontend/server/src/main/java/org/pytorch/serve/ensemble/Dag.java
> +}
Refactor to use Guava Graph lib - https://guava.dev/releases/23.0/api/docs/com/google/common/graph/Graph.html

2021-02-09 22:48 UTC, dhanainme commented on frontend/server/src/main/java/org/pytorch/serve/ensemble/DagExecutor.java
> +}
ListenableFuture may be a more appropriate 

https://guava.dev/releases/21.0/api/docs/com/google/common/util/concurrent/ListenableFuture.html

https://stackoverflow.com/questions/19138212/how-to-implement-a-dag-like-scheduler-in-java has a good example.

2021-02-09 22:48 UTC, dhanainme commented on frontend/server/src/main/java/org/pytorch/serve/ensemble/NodeOutput.java
> +    }
Lombok

2021-02-09 22:48 UTC, dhanainme commented on frontend/server/src/main/java/org/pytorch/serve/ensemble/WorkflowManifest.java
> +    private Workflow workflow;
final / lombok

2021-02-09 22:48 UTC, dhanainme commented on frontend/server/src/main/java/org/pytorch/serve/ensemble/WorkflowModel.java
> +    private String handler;
final / lombok

2021-02-09 23:09 UTC, dhanainme requested changes
Reviewed code for archiver CLI 

Callouts 

* Document behavior for what gets zipped up explicitly. 

Integ test code has not been reviewed yet.

2021-02-09 23:09 UTC, dhanainme commented on workflow-archiver/workflow_archiver/workflow_packaging_utils.py
> +                dst.write(file_path, os.path.relpath(file_path, path))
May have to explicitly document this behavior on what files get archived.

2021-02-09 23:09 UTC, dhanainme commented on workflow-archiver/workflow_archiver/workflow_packaging_utils.py
> +            raise WorkflowArchiverError("Given export-path {} is not a directory. "
Nit : Separate methods for single method calls which can be grouped.

2021-02-09 23:17 UTC, dhanainme requested changes

2021-02-09 23:17 UTC, dhanainme commented on ts/arg_parser.py
> +                            help='Workflow store location from where local or default workflows can be loaded')
Q : Why 2 stores ? Why not just 1 dir for both models & workflow.

2021-03-25 20:52 UTC, HamidShojanazeri reviewed
@dhanainme Please refer to inline comments.

2021-03-25 20:52 UTC, HamidShojanazeri commented on examples/Workflows/densenet_image_classifier_pipeline/densenet_model/densenet_handler.py
> +"""
@dhanainme We need to document/add user guide for the differences of the handler for models(nodes) in the workflow with regular handlers we have in the non-workflow use-cases.

2021-03-25 20:52 UTC, HamidShojanazeri commented on docs/workflows.md
> +A workflow specification is a YAML file which provides the details of the models to be executed and a DAG for defining data flow.
@dhanainme Please add some clarification on how the gpu assignment would be handled here.

2021-03-25 20:52 UTC, HamidShojanazeri commented on ts/torch_handler/densenet_handler.py
> +"""
@dhanainme is this planned to be aded as default handler? or having it in the example would suffice.

2021-03-25 21:23 UTC, HamidShojanazeri commented
@dhanainme I was wondering in case having multiple models in the DAG, then we will have one worker-manager that have a copy of all the models + CUDA runtime?

2021-05-06 18:52 UTC, msaroufim commented
Hi I'm new so lacking context

This PR seems to be about adding sequential workflows but just trying to understand how this differs in scope from a regular handler? https://github.com/pytorch/serve/blob/master/examples/Huggingface_Transformers/Transformer_handler_generalized.py

Is the intention that this PR makes it easier to support non sequential workflows in the future?

2021-05-06 19:15 UTC, HamidShojanazeri commented
> Hi I'm new so lacking context
> 
> This PR seems to be about adding sequential workflows but just trying to understand how this differs in scope from a regular handler? https://github.com/pytorch/serve/blob/master/examples/Huggingface_Transformers/Transformer_handler_generalized.py
> 
> Is the intention that this PR makes it easier to support non sequential workflows in the future?

@msaroufim Initially, we were targeting with sequential pipeline support for this release and adding support for other workflow DAGs in next releases. The current status of the PR, merged into release_0.4.0 branch supports non-sequential as well, although we are looking into improvements in future releases.

2021-05-19 21:54 UTC, merged