[WIP] Apache benchmarks made dynamic
pytorch/serve pull request #905
Opened 2020-12-15 15:08 UTC by abishekchiffon

## Description

Made the following changes in the apache benchmarks to make it more dynamic.
1. Config.properties can be dynamically set on run
2. inference_model_url can be dynamically set on run
3. inference_url and ports are made to be taken dynamically from the config.properties

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

- Logs
[gpu_mnist_explanations_kf.log](https://github.com/pytorch/serve/files/5696726/gpu_mnist_explanations_kf.log)
[gpu_mnist_explnations_ts.log](https://github.com/pytorch/serve/files/5696727/gpu_mnist_explnations_ts.log)
[gpu_mnist_predictions_kf.log](https://github.com/pytorch/serve/files/5696728/gpu_mnist_predictions_kf.log)
[gpu_mnist_predictions_ts.log](https://github.com/pytorch/serve/files/5696729/gpu_mnist_predictions_ts.log)
[gpu_resnet_predictions.log](https://github.com/pytorch/serve/files/5696730/gpu_resnet_predictions.log)

## Checklist:

- [x] Have you added tests that prove your fix is effective or that this feature works?
- [x] New and existing unit tests pass locally with these changes?
- [x] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

2020-12-17 04:50 UTC, harshbafna approved these changes

2020-12-17 05:33 UTC, maaquib approved these changes

2020-12-17 06:03 UTC, harshbafna requested changes
@abishekchiffon Please address the following:

 - Update documentation to run benchmarking with KFServing APIs
 - Add steps to run this with docker container
 - Attach log for run with cofig.json file with new parameters
 - Attach logs for runs on docker container

2020-12-17 16:55 UTC, abishekchiffon commented
> @abishekchiffon Please address the following:
> 
> * Update documentation to run benchmarking with KFServing APIs
> * Add steps to run this with docker container
> * Attach log for run with cofig.json file with new parameters
> * Attach logs for runs on docker container

@harshbafna 
* Updated documentation to run benchmarking with KFServing APIs
* Added steps to run this with docker container
* Attached log for run with cofig.json file with new parameters
* Attached logs for runs on docker container
* The apache bench docker worked after building from local.

2020-12-18 21:30 UTC, dhanainme approved these changes

2020-12-18 21:31 UTC, merged