add googlenet into image classifier example
pytorch/serve pull request #936
Opened 2021-01-09 18:35 UTC by tigercosmos

## Description

This PR adds the googlenet into `example/image_classifier`

## Type of change

add an example

## Checklist:

- [X] Have you added tests that prove your fix is effective or that this feature works?
- [X] New and existing unit tests pass locally with these changes?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [X] Have you made corresponding changes to the documentation?

2021-04-22 15:25 UTC, msaroufim commented
Thank you for your contribution. I think your PR made me realize that it may be best to refactor one of the existing examples to make it easier to support new models. Let me know if you'd like to take a stab at it because 50 lines of documentation for 3 lines of code for each new model doesn't make the most sense

2021-04-22 17:16 UTC, tigercosmos commented
@msaroufim I strongly agree with your point. However, I am afraid that I don't have time to put more effort into this refactoring.

2021-04-30 05:42 UTC, msaroufim commented
That's fair, I opened up another issue to track the code duplication issue #1047 so I think we can pull this example in. Thank you for your contribution to Pytorch!

2021-04-30 05:43 UTC, msaroufim approved these changes

2021-05-13 17:21 UTC, HamidShojanazeri requested changes
Thanks @tigercosmos for your contribution, please refer to the inline comments.

2021-05-13 17:21 UTC, HamidShojanazeri commented on examples/image_classifier/googlenet/README.md
> +1. Save model using scripting
@tigercosmos running the torchscript version, facing this [error](https://gist.github.com/HamidShojanazeri/f49b3f79a981d5b89bcf3cbac33c6f65) on post-processing. Wonder if you can repro, on your end.

2021-05-13 17:21 UTC, HamidShojanazeri commented on examples/image_classifier/googlenet/README.md
> +2. Save model using tracing
@tigercosmos I haven't been able to trace the mode, failing with assertion [error](https://gist.github.com/HamidShojanazeri/9ac3cfaad8d214770090edbd97b24c31) in trace.

2021-05-13 17:21 UTC, HamidShojanazeri commented on examples/image_classifier/googlenet/README.md
> +    torchserve --start --model-store model_store --models googlenet
@tigercosmos Please change to --models googlenet = googlenet.mar

2021-06-09 04:52 UTC, closed without merging